### ISSUE TITLE
Handling warning with Java exception in destructor

### ISSUE THREAD

**Issue by shiqin-liu** [AccessibilityObservatory/BikeAccess#1]
Java Exception Error occurs at the end of the result log:

```
    Calculated travel time matrix using approximately 16 seconds
    Output results were saved in blocks_to_trail_access_points_lts2.csv
Exception in thread "MapDB shutdown hook" java.lang.RuntimeException: java.lang.InterruptedException
	at org.mapdb.AsyncWriteEngine.close(AsyncWriteEngine.java:443)
	at org.mapdb.EngineWrapper.close(EngineWrapper.java:81)
	at org.mapdb.Caches$HashTable.close(Caches.java:328)
	at org.mapdb.EngineWrapper.close(EngineWrapper.java:81)
	at org.mapdb.EngineWrapper$CloseOnJVMShutdown.close(EngineWrapper.java:586)
	at org.mapdb.EngineWrapper$CloseOnJVMShutdown$1.run(EngineWrapper.java:571)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1081)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
	at org.mapdb.AsyncWriteEngine.close(AsyncWriteEngine.java:435)
	... 6 more
Exception ignored in: <function TransportNetwork.__del__ at 0x126d705e0>
Traceback (most recent call last):
  File "/Users/ssliu/.pyenv/versions/nae/lib/python3.10/site-packages/r5py/r5/transport_network.py", line 116, in __del__
RuntimeError: Unable to import 'java.lang.System' without JVM
```

This has been reported and addressed by upstream software R5py https://github.com/r5py/r5py/pull/368; that involves some update on the software dependencies. Currently this warning does not affect the actual calculation process and results, it is not urgent but we would follow up to address the issue.

**Comment by shiqin-liu** [comment]
The above error is solved in the new r5py 0.1.1 release, yet another related issues occurs:
```
Exception in thread "MapDB shutdown hook" java.lang.RuntimeException: java.lang.InterruptedException
	at org.mapdb.AsyncWriteEngine.close(AsyncWriteEngine.java:443)
	at org.mapdb.EngineWrapper.close(EngineWrapper.java:81)
	at org.mapdb.Caches$HashTable.close(Caches.java:328)
	at org.mapdb.EngineWrapper.close(EngineWrapper.java:81)
	at org.mapdb.EngineWrapper$CloseOnJVMShutdown.close(EngineWrapper.java:586)
	at org.mapdb.EngineWrapper$CloseOnJVMShutdown$1.run(EngineWrapper.java:571)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1081)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1369)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
	at org.mapdb.AsyncWriteEngine.close(AsyncWriteEngine.java:435)
	... 6 more
Exception ignored in: <function TransportNetwork.__del__ at 0x16a1745e0>
Traceback (most recent call last):
  File "/Users/ssliu/.pyenv/versions/nae/lib/python3.10/site-packages/r5py/r5/transport_network.py", line 116, in __del__
RuntimeError: Unable to import 'java.lang.System' without JVM
```

Reported in https://github.com/r5py/r5py/issues/388

**Comment by shiqin-liu** [comment]
issue resolved through https://github.com/r5py/r5py/pull/391, expecting new release
